# This GitHub Actions workflow runs the tests that target the application.

name: Run tests

on:
  push: { branches: [ main ] }
  workflow_dispatch: { }
  pull_request: { }
  # Allow this workflow to be called by other workflows.
  # Reference: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call: { }

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM dependencies
        run: npm ci
      - name: Run tests
        run: npm test
